package com.example.android.tourguide;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;

import java.util.ArrayList;

public class religious_places extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_lakes);

        final ArrayList<listItem> listk = new ArrayList<listItem>();
        listk.add(new listItem("1.","Tungnath",R.drawable.tungnath,"Tungnath is the highest Shiva temple in the world and is the highest of the five Panch Kedar temples located in the mountain range of Tunganath in Rudraprayag district, in the Indian state of Uttarakhand. The Tunganath (literal meaning: Lord of the peaks) mountains form the Mandakini and Alaknanda river valleys. Located at an altitude of 3,680 m (12,073 ft), and just below the peak of Chandrashila.",30.488718,79.217010));
        listk.add(new listItem("2.","Mansa Devi Temple",R.drawable.mansadevi,"Mansa Devi Temple, Haridwar (Hindi: मंसा देवी मंदिर, हरिद्वार) is a Hindu temple dedicated to goddess Mansa Devi in the holy city of Haridwar in the Uttarakhand state of India. The temple is located atop the Bilwa Parvat[1][2] on the Sivalik Hills, the southernmost mountain chain of the Himalayas. The temple also known as Bilwa Tirth is one of the Panch Tirth (Five Pilgrimages) within Haridwar."+"The temple is known for being the holy abode of Manasa, a form of Shakti and is said to have emerged from the mind of the lord Shiva. Mansa is regarded as the sister of the Nāga (serpent) Vasuki. The term Mansa means wish and it is believed that the goddess fulfils all the wishes of a sincere devotee. Devotees who want their wishes to be fulfilled by Mansa tie threads to the branches of a tree located in the temple. Once their wishes are fulfilled, people come back again to the temple to untie the thread from the tree. Mansa is also offered coconuts, fruits, garlands and incense sticks in order to appease her.",29.933733,78.180158));
        listk.add(new listItem("3.","Chandi Devi Temple",R.drawable.chandidevi,"Chandi Devi Temple, Haridwar (Hindi: चण्डी देवी मंदिर, हरिद्वार) is a Hindu temple dedicated to Goddess Chandi Devi in the holy city of Haridwar in the Uttarakhand state of India. The temple is situated atop the Neel Parvat on the Eastern summit of the Sivalik Hills, the southernmost mountain chain of the Himalayas. Chandi Devi Temple was built in 1929 by Suchat Singh in his reign as the King of Kashmir. However, the main murti of Chandi Devi at the temple is said to have been installed in the 8th century by Adi Shankaracharya, one of the greatest priests of Hindu religion.[1][2] The temple also known as Neel Parvat Teerth is one of the Panch Tirth (Five Pilgrimages) located within Haridwar."+
                "Chandi Devi Temple is highly revered by devotees as a Siddh Peetha which is a place of worship where desires get fulfilled. It is one of three such Peethas located in Haridwar, the other two being Mansa Devi Temple and Maya Devi Temple.",29.933733,78.180158));
        listk.add(new listItem("4.","Badrinath Temple",R.drawable.badrinath,"Badrinath or Badrinarayan Temple is a Hindu temple dedicated to Vishnu which is situated in the town of Badrinath in Uttarakhand, India. The temple and town form one of the four Char Dham and Chota Char Dham pilgrimage sites. The temple is also one of the 108 Divya Desams dedicated to Vishnu, who is worshipped as Badrinath—holy shrines for Vaishnavites. It is open for six months every year (between the end of April and the beginning of November), because of extreme weather conditions in the Himalayan region. The temple is located in Garhwal hill tracks in Chamoli district along the banks of Alaknanda River at an elevation of 3,133 m (10,279 ft) above the mean sea level. It is one of the most visited pilgrimage centres of India, having recorded 1,060,000 visits."+
                "The image of the presiding deity worshipped in the temple is a 1 m (3.3 ft) tall, black stone statue of Vishnu in the form of Badrinarayan. The statue is considered by many Hindus to be one of eight swayam vyakta kshetras, or self-manifested statues of Vishnu.[1]"+
                "Mata Murti Ka Mela, which commemorates the descent of river Ganges on mother earth, is the most prominent festival celebrated in the Badrinath Temple. Although Badrinath is located in North India, the head priest, or Rawal, is traditionally a Nambudiri Brahmin chosen from the South Indian state of Kerala. The temple was included in the Uttar Pradesh state government Act No. 30/1948 as Act no. 16,1939, which later came to be known as Shri Badarinath and Shri Kedarnath Mandir Act. The committee nominated by the state government administers both the temples and has seventeen members on its board.",30.744787,79.491067));
        listk.add(new listItem("5.","Kedarnath Temple",R.drawable.kedarnath,"Kēdārnāth Mandir (Kedarnath Temple) is a Hindu temple dedicated to Lord Shiva. It is on the Garhwal Himalayan range near the Mandakini river in Kedarnath, Uttarakhand in India. Due to extreme weather conditions, the temple is open only between the end of April (Akshaya Tritriya) to Kartik Purnima (the autumn full moon, usually November). During the winters, the vigrahas (deities) from Kedarnath temple are brought to Ukhimath and worshipped there for six months. Lord Shiva is worshipped as Kedarnath, the 'Lord of Kedar Khand', the historical name of the region.[1]"+"The unstable temple is not directly accessible by road and has to be reached by a 18 kilometres (11 mi) uphill trek from Gaurikund. Pony and manchan service is available to reach the structure. The temple was built by Pandavas and revived by Adi Sankaracharya and is one of the twelve Jyotirlingas, the holiest Hindu shrines of Shiva. It is one of the 275 Paadal Petra Sthalams, expounded in Tevaram. Pandavas were supposed to have pleased Shiva by doing penance in Kedarnath. The temple is one of the four major sites in India's Chota Char Dham pilgrimage of Northern Himalayas. This temple is the highest among the 12 Jyotirlingas.[2] Kedarnath was the worst affected area during the 2013 flash floods in North India. The temple complex, surrounding areas and Kedarnath town suffered extensive damage, but the temple structure did not suffer any \"major\" damage, apart from a few cracks on one side of the four walls which was caused by the flowing debris from the higher mountains. A large rock among the debris acted as a barrier, protecting the temple from the flood. The surrounding premises and other buildings in market area were heavily damaged.",30.735249,79.066874));
        listk.add(new listItem("6.","Har ki Pauri",R.drawable.harkipauri,"Jai Ganga Maa Har Ki Pauri (Hindi: हर की पौड़ी) is a famous ghat on the banks of the Ganges in Haridwar in the Indian state of Uttarakhand. This revered place is the major landmark of the holy city of Haridwar. Literally, \"Har\" means \"Lord Shiva\" who is the god according to shaivite Rishav Bhagwan school of Hindu theology, \"Ki\" means \"of\" and \"Pauri\" means \"steps\". Lord Shiva and Lord Vishnu are believed to have visited the Brahmakund in Har Ki Pauri in the Vedic times. There is a large footprint said to belong to Lord Vishnu on a stone wall."+
                "It is believed that it is precise spot where the Ganges leaves the mountains and enters the plains. The ghat is on the west bank of Ganges canal through which the Ganges is diverted just to the north. Har Ki Pauri is also the area where thousands of pilgrims converge and the festivities commence during the Kumbha Mela, which takes place every twelve years, and the Ardh Kumbh Mela, which takes place every six years and the Punjabi festival of Vaisakhi, a harvest festival occurring every year in the month of April ."+
                "Haridwar is famous for Har ki Pauri and it's Ganga Aarti. Ganga aarti means worship of Ganga. Lots of people visit this place for Ganga aarti everyday at 06:00 PM.",29.956147,78.170968));
        listk.add(new listItem("7.","Tapkeshwar Temple",R.drawable.tapkeshwar,"The Shiva linga is in a cave nearby where the river enters and water droplets drip down on the Shivalinga. The small cave with this splendid scenery is said to have been once resided by Dronacharya- the teacher of Pandavas and Kauravas in the Hindu epic Mahabharata written by Ved Vyas. The cave is thus named Drona Cave after his name. Tapkeshwar Temple in Dehradun, also known as Tapkeshwar Mahadev Temple, is one of the most famous temples dedicated to Lord Shiva. Situated by the forest side, the main shivalinga at the temple is inside a natural cave. Water drops from the ceiling of the cave trickle down over the shivalinga in a continuous downpour, making for an interesting spectacle. Tourists in Dehradun visit Tapkeshwar Mahadev temple hardly 6 km from the main city. Tapkeshwar Mahadev temple is the nearest widely popular pilgrimage in Dehradun. The beautiful temple of lord Shiva established in between the two hills attracts hundreds of tourists from and around Dehradun every month. Travelers from and around Uttarakhand state pay visit to Tapkeshwar Mahadev temple for its religious significance and adventurers go to see the water drops dripping in the Shiva ling in Drona cave. The water that drops down vanishes underground and can be seen only few yards away in the form of a stream. In Tapkeshwar Mahadev temple, cool sulphur-water springs where devoted pilgrims take bath before entering the temple.",30.357294,78.016683));
        listk.add(new listItem("8.","Neelkanth Mahadev Temple",R.drawable.neelkanth,"Tourists in Dehradun visit Tapkeshwar Mahadev temple hardly 6 km from the main city. Tapkeshwar Mahadev temple is the nearest widely popular pilgrimage in Dehradun. The beautiful temple of lord Shiva established in between the two hills attracts hundreds of tourists from and around Dehradun every month. Travelers from and around Uttarakhand state pay visit to Tapkeshwar Mahadev temple for its religious significance and adventurers go to see the water drops dripping in the Shiva ling in Drona cave. The water that drops down vanishes underground and can be seen only few yards away in the form of a stream. In Tapkeshwar Mahadev temple, cool sulphur-water springs where devoted pilgrims take bath before entering the temple. According to Hindu mythology, the place where the Neelkanth Mahadev Temple currently stands is the sacred location where Lord Shiva consumed the poison that originated from the sea when Devas (Gods) and Asuras (Demons) churned the ocean in order to obtain Amrita. This poison that emanated during the Samudramanthan (churning of ocean) made his throat blue in color. Thus, Lord Shiva is also known as Neelkanth, literally meaning The Blue Throated One.",30.080724,78.341001));
        listk.add(new listItem("9.","Surkunda Devi",R.drawable.surkundadevi,"Surkanda Devi is a Hindu temple situated close to the small resort hamlet of Dhanaulti in Tehri District. It is at an altitude of about 2,757 metres, or 9976 ft; lies close to nearby hill stations of Dhanaulti (8 km) and Chamba (22 km)& walking distance of approx 3 km from Kaddukhal, the place where vehicles are parked."+
                "It is surrounded by dense forests and affords a scenic view of the surrounding region including the Himalayas to the north, and certain cities to the south (e.g., Dehradun, Rishikesh) The Ganga Dussera festival is celebrated every year between May and June and attracts a lot of people.",30.411419,78.288756));
        listk.add(new listItem("10.","Piran Kaliyar Sharif",R.drawable.pirankalyarsharif,"Piran Kaliyar is the dargah of 13th-century Sufi saint of Chishti Order, Alauddin Ali Ahmed Sabir Kalyari also known as Sarkar Sabir Pak and Sabir Kaliyari, situated at Kaliyar village, near Haridwar on the banks of Ganga Canal, 7 km. from Roorkee,[1] It is one of the most revered shrine for Muslims in India and is equally revered by Hindus and Muslims. The dargah shrine built by Ibrahim Lodhi, an Afghan ruler of Delhi,"+
                "He was the Sufi Saint of Chishti Order in the 13th century, a successor to Baba Farid (1188–1280), and the first in the Sabiriya branch of Chishti Order.",29.926259,77.943412));

        listAdapter ld = new listAdapter(religious_places.this, listk);
        ListView listView = (ListView)findViewById(R.id.lakes);
        listView.setAdapter(ld);


        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                listItem etc = listk.get(position);
                String pn = etc.getPlaceName();
                String pi = etc.getPlaceInfo();
                int pp = etc.getPlacePic();
                double d1 = etc.getD1();
                double d2 = etc.getD2();
                Intent i = new Intent(religious_places.this, Particular.class);
                i.putExtra("placeName", pn);
                i.putExtra("placeInfo", pi);
                i.putExtra("placePic", pp);
                i.putExtra("placeD1",d1);
                i.putExtra("placeD2",d2);
                startActivity(i);
            }
        });

    }
}
